### ISSUE TITLE
The generate gzip executable fails on some gzip files while "normal" gzip happily decompresses them.

### ISSUE THREAD

**Issue by EraYaN** [ebiggers/libdeflate#31] opened 2017-10-08 15:59 UTC
The used file are form the common crawl.

`https://commoncrawl.s3.amazonaws.com/crawl-data/CC-MAIN-2017-39/segments/1505818685129.23/wet/CC-MAIN-20170919112242-20170919132242-00000.warc.wet.gz` 

The files seem to have a bad size descriptor at the end, but the program (and an implementation of the library) give and error about "Not enough space in the output buffer" value 3 I think.

And the generated gzip gives `file corrupt or not in gzip format`

While OS gzip and stuff like zlib (custom implementation or gzstream) WinRar and most other seem to work just fine.

**Comment by ebiggers** [comment] 2017-10-09 00:34
The problem is that libdeflate's gzip program doesn't support multi-member gzip files (files with multiple gzip streams concatenated to each other).  However, after looking into it, I found there is a way to support them that was not too hard.  I've pushed a fix to the branch "multi_member_gzip".  Feel free to try it, but I need to do a bit more review and testing before pushing it to the master branch.

**Comment by EraYaN** [comment] 2017-10-10 08:24
Well the executable creates the exact same file as the OS gzip, I will try a custom implementation too.

**Comment by ebiggers** [comment] 2017-11-20 08:46
Commit 5a9d25a8922e2d74618fba96e56db4fe145510f4 added multi-member gzip file support.

**Closed by ebiggers** 2017-11-20 08:46 UTC
