### ISSUE TITLE
MinGW_w64 make errors with cr and libdeflate.lib

### ISSUE THREAD

**Issue by JoeArizona** [ebiggers/libdeflate#26] opened 2017-05-01 02:47 UTC
On a new machine (Windows 10), I'm getting the following errors when trying to build:

```
PS C:\Repos\libdeflate-master> C:\mingw64-win32\bin\mingw32-make.exe CC=x86_64-w64-mingw32-gcc-6.3.0
  CC       lib/aligned_malloc.o
  CC       lib/deflate_decompress.o
  CC       lib/x86_cpu_features.o
  CC       lib/deflate_compress.o
  CC       lib/adler32.o
  CC       lib/zlib_decompress.o
  CC       lib/zlib_compress.o
  CC       lib/crc32.o
  CC       lib/gzip_decompress.o
  CC       lib/gzip_compress.o
  AR       libdeflate.lib
x86_64-w64-mingw32-gcc-6.3.0.exe: error: cr: No such file or directory
x86_64-w64-mingw32-gcc-6.3.0.exe: error: libdeflate.lib: No such file or directory
Makefile:122: recipe for target 'libdeflate.lib' failed
mingw32-make: *** [libdeflate.lib] Error 1
```

I don't understand what **cr** is, but **libdeflate.lib** seems to be part of the cleaning phase. Any idea how to get past these?

FYI, I'm using MinGW_w64 obtained from [this official page](https://sourceforge.net/projects/mingw-w64/files/), specifically the **x86_64-win32-seh** version.

**Comment by ebiggers** [comment] 2017-05-01 04:12
This should be fixed by 1f8090cda17785c300aa11e834ad7744cf4b9e80; the problem was that the Makefile did not correctly detect the `ar` program to use.  I'm surprised it even got that far, though, since that MinGW distribution doesn't include standard UNIX tools such as `sh` (you must have them somewhere else on your path).

**Comment by JoeArizona** [comment] 2017-05-04 02:11
Now I'm getting a slightly different error, one that actually talks about `ar` (where before it complained about `cr`). `ar` is on the path, in the same directory as the make executable I'm calling, so I'm confused.

I have `sh` on a system path with a separate Git install. I'll give you a paths dump in a minute, but first here's the new error (it's less blurry if you click on it):

![libdeflate build error on akio](https://cloud.githubusercontent.com/assets/8071692/25688334/1a3d0764-3033-11e7-9781-55695a0e8b9f.PNG)

A screenshot wouldn't fit all the contents, so I dumped everything in main directory into a text file:

```
"C:\mingw64-6.3.0-Win32-SEH\bin\dwp.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\elfedit.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\g++.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\gcc.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\gcc-ar.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\gcc-nm.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\gcc-ranlib.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\gcov.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\gcov-tool.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\gdb.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\gdborig.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\gdbserver.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\gendef.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\genidl.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\genpeimg.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\gfortran.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\gprof.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\ld.bfd.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\ld.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\ld.gold.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\libatomic-1.dll"
"C:\mingw64-6.3.0-Win32-SEH\bin\libgcc_s_seh-1.dll"
"C:\mingw64-6.3.0-Win32-SEH\bin\libgfortran-3.dll"
"C:\mingw64-6.3.0-Win32-SEH\bin\libgomp-1.dll"
"C:\mingw64-6.3.0-Win32-SEH\bin\libquadmath-0.dll"
"C:\mingw64-6.3.0-Win32-SEH\bin\libssp-0.dll"
"C:\mingw64-6.3.0-Win32-SEH\bin\libstdc++-6.dll"
"C:\mingw64-6.3.0-Win32-SEH\bin\libwinpthread-1.dll"
"C:\mingw64-6.3.0-Win32-SEH\bin\mingw32-make.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\nm.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\objcopy.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\objdump.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\ranlib.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\readelf.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\size.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\strings.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\strip.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\widl.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\windmc.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\windres.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\x86_64-w64-mingw32-c++.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\x86_64-w64-mingw32-g++.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\x86_64-w64-mingw32-gcc.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\x86_64-w64-mingw32-gcc-6.3.0.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\x86_64-w64-mingw32-gcc-ar.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\x86_64-w64-mingw32-gcc-nm.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\x86_64-w64-mingw32-gcc-ranlib.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\x86_64-w64-mingw32-gfortran.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\addr2line.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\ar.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\as.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\c++.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\c++filt.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\cpp.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\dlltool.exe"
"C:\mingw64-6.3.0-Win32-SEH\bin\dllwrap.exe"

```

And here are my Git\bin contents:

```
"C:\Program Files\Git\bin\git.exe"
"C:\Program Files\Git\bin\sh.exe"
"C:\Program Files\Git\bin\bash.exe"
```

I manually added the above Git\bin path to my environment variables a while back. When Git for Windows is installed, it doesn't add that bin directory to the path – it only adds the cmd directory. This probably doesn't matter, but here's what's in it:

```
"C:\Program Files\Git\cmd\gitk.exe"
"C:\Program Files\Git\cmd\start-ssh-agent.cmd"
"C:\Program Files\Git\cmd\start-ssh-pageant.cmd"
"C:\Program Files\Git\cmd\git.exe"
"C:\Program Files\Git\cmd\git-gui.exe"
```

I don't understand the error – why doesn't it detect `ar`?

**Comment by ebiggers** [comment] 2017-05-04 02:32
Okay, that's weird.  Normally binutils would be installed with the `x86_64-w64-mingw32-` prefix to go along with `x86_64-w64-mingw32-gcc.exe`, but that MinGW distribution is missing them.

Can you try just setting the compiler to `gcc`?  I think that would make this a lot easier.

**Comment by ebiggers** [comment] 2017-05-26 02:46
Can you see if it works with `make CC=gcc`?

It's already documented in the libdeflate README that this is required for some MinGW distributions.

If it works, I don't think there's much else I can do.

**Comment by JoeArizona** [comment] 2017-05-29 05:13
Now I'm seeing this:

> PS C:\Repos\libdeflate-master> C:\mingw64-win32\bin\mingw32-make.exe CC=gcc
> -Wpedantic was unexpected at this time.
> -Wdeclaration-after-statement was unexpected at this time.
> -Wmissing-prototypes was unexpected at this time.
> -Wstrict-prototypes was unexpected at this time.
> -Wvla was unexpected at this time.
> The system cannot find the path specified.
> 'flags' is not recognized as an internal or external command,
> operable program or batch file.
> Makefile:138: recipe for target '.lib-cflags' failed
> mingw32-make: *** [.lib-cflags] Error 1

I think we've seen this one before, but I don't remember the details of the solution or root cause. Once I dig into it, I think it will be an easy fix, but right now it looks like I took a few steps back – it's not getting near as far as it did before.

I have three different MinGWs installed, and I'm getting the above error(s) with all three, using CC=gcc, and trying both the `mingw32-make.exe` and the vanilla `make.exe` in the distros that have both. Maybe this is an `sh` issue. I feel like I'm missing something basic. I did recently upgrade these machines from Home to Pro editions of Win 10 to get access to Hyper-V, which had surprising side effects, reset some things, destroyed my Fedora partitions, etc., but I'm not sure what would affect this. Maybe I should just try the `Makefile.msc`?

**Comment by ebiggers** [comment] 2017-05-29 05:54
Yes you ran into that problem before: https://github.com/ebiggers/libdeflate/issues/15.  Whatever MinGW distribution you're using doesn't include a UNIX `sh`.  (And it's probably missing other standard tools as well.)

I'll probably need to document that Cygwin or MSYS is required, not just any random "MinGW".

**Comment by JoeArizona** [comment] 2017-06-01 16:57
What was the magic with MSYS(2)? If just try make, I get the `command not found` error below. I thought make was part of the whole ball of wax with MSYS2 and it shell.

![msys2 libdeflate make](https://cloud.githubusercontent.com/assets/8071692/26691051/964a52ba-46b0-11e7-9db9-7752ca6c5161.PNG)

**Comment by JoeArizona** [comment] 2017-06-01 17:01
Scratch that. I have to install make separately using pacman. I might also have to install gcc. I don't understand what MSYS2 comes with, if not make and gcc, but whatever. I'll update when I'm past those hurdles.

**Comment by JoeArizona** [comment] 2017-06-01 17:07
Okay, after installing make and gcc 6.3, this is what happen. At the bottom appear to be errors, but they're not clearly labeled as such in every case. I don't have gzip.exe in the repo, so I assume the errors prevented full compilation:

> Blue@Akio MINGW64 /c/Repos/libdeflate-master
> $ make
> Rebuilding library due to new compiler flags
>   CC       lib/aligned_malloc.o
>   CC       lib/deflate_decompress.o
>   CC       lib/x86_cpu_features.o
>   CC       lib/deflate_compress.o
>   CC       lib/adler32.o
>   CC       lib/zlib_decompress.o
>   CC       lib/zlib_compress.o
>   CC       lib/crc32.o
>   CC       lib/gzip_decompress.o
>   CC       lib/gzip_compress.o
>   AR       libdeflate.a
>   CC       lib/aligned_malloc.shlib.o
>   CC       lib/deflate_decompress.shlib.o
>   CC       lib/x86_cpu_features.shlib.o
>   CC       lib/deflate_compress.shlib.o
>   CC       lib/adler32.shlib.o
>   CC       lib/zlib_decompress.shlib.o
>   CC       lib/zlib_compress.shlib.o
>   CC       lib/crc32.shlib.o
>   CC       lib/gzip_decompress.shlib.o
>   CC       lib/gzip_compress.shlib.o
>   CCLD     libdeflate.so
>   GEN      programs/config.h
>   CC       programs/gzip.o
> In file included from /usr/include/errno.h:9:0,
>                  from programs/gzip.c:30:
> /usr/include/sys/errno.h:25:23: error: conflicting types for ‘program_invocation_name’
>  extern __IMPORT char *program_invocation_name;
>                        ^~~~~~~~~~~~~~~~~~~~~~~
> In file included from programs/gzip.c:28:0:
> programs/prog_util.h:117:21: note: previous declaration of ‘program_invocation_name’ was here
>  extern const tchar *program_invocation_name;
>                      ^~~~~~~~~~~~~~~~~~~~~~~
> programs/gzip.c: In function ‘main’:
> programs/gzip.c:493:26: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
>   program_invocation_name = get_filename(argv[0]);
>                           ^
> make: *** [Makefile:174: programs/gzip.o] Error 1

**Comment by ebiggers** [comment] 2017-06-02 01:39
Well, I haven't personally used MSYS2 before, but like Cygwin it appears to have different packages you can install, so if the packages needed to compile C programs are not installed by default (and they very well may not be, since people may need a UNIX-like environment for different reasons) you'd need to install them using the package manager.  As for the conflicting declaration of `program_invocation_name` in `errno.h`, I don't know why that happens; normally that should only be exposed to programs that request to be compiled with GNU extensions by defining `_GNU_SOURCE`, and I didn't think it even existed on Windows.

When I have a chance I'll try to figure out what the problem is and also put together step-by-step directions for MSYS2 and Cygwin (unless you want to get to it first).

**Comment by ebiggers** [comment] 2017-06-02 05:53
I've updated the documentation for building libdeflate for Windows; see https://github.com/ebiggers/libdeflate/tree/dev.  Can you test the directions for MSYS2 (or Cygwin too, if you want) before I push it to "master", to see if I forgot to explain anything important?  Note in particular that with MSYS2 it's necessary to install the MinGW packages and open a "MSYS2 MinGW" shell, not simply install "gcc" and use it in the main shell which I think you were doing.

**Comment by JoeArizona** [comment] 2017-06-07 14:35
Okay, a few things:

1. MSYS2 seems to work with your new instructions. Everything builds. (I haven't tried actually _running_ the program yet, i.e. compressing files.)
2. I was already using the MSYS2 shell, or one of them. There are three, two of which have MinGW in their names. See the attached screenshot.
3. What made the difference was installing those awkwardly named `mingw-w64-x86_64-...` packages, per your instructions.
4. I ignored your instructions to install the 32-bit versions (`mingw-w64-i686-...`). It works fine for me to just install the 64-bit ones. Is there a particular reason you instruct people to install both?
5. I don't think people actually have to run an "MSYS2 MinGW" shell. I think the "MSYS2 MSYS" shell works just as well. Again, see the screenshot for the three shells.
6. I think the Windows nmake/Visual Studio instruction fails, based on my prior experience from a few months back. I had a whole write-up of all the actually necessary steps, and I'll dig into that again and let you know what the current state of affairs is. Visual Studio 2017, which I'm now using, is supposed to have a simple "compile any C/C++ program" sort of functionality now, but I need to research it.

**Comment by ebiggers** [comment] 2017-06-10 02:23
I've committed the instructions some slight tweaks.  To answer some of your observations:

> I ignored your instructions to install the 32-bit versions (mingw-w64-i686-...). It works fine for me to just install the 64-bit ones. Is there a particular reason you instruct people to install both? (Note that the screenshot shows both 32-bit and 64-bit shells – these appear by default from just the initial install of MSYS2, and is not the result of installing any packages.)

The mingw-w64-i686 packages are only needed if you are compiling 32-bit binaries.  I added a note to the instructions.

> I don't think people actually have to run an "MSYS2 MinGW" shell. I think the "MSYS2 MSYS" shell works just as well. Again, see the screenshot for the three shells.

Are you sure?  The MinGW compiler is in `/mingw64/bin/`, which isn't even on the $PATH in the "main" shell, so there's no way it could possibly have worked in the "main" shell unless you did some manual steps to set up the environment properly.  And if you compiled it with `/usr/bin/gcc` in the "main" shell (which would require installing the `gcc` package which the directions don't say to do, and fails anyway because of the `program_invocation_name` error), it wouldn't be correct either because the resulting binaries would be linked to the MSYS2 DLL, rather than being standalone Windows binaries.

> I think the Windows nmake/Visual Studio instruction fails, based on my prior experience from a few months back.

If it actually doesn't work then please open a bug, with details, or (even better) propose a patch to fix the problem.

**Closed by ebiggers** 2017-06-10 02:23 UTC

**Comment by JoeArizona** [comment] 2017-06-17 00:50
I'll double-check on the MSYS shell, and I'll revisit the Windows workflow this weekend.

Separately, can you e-mail me at jose.duarte@asu.edu so that I can e-mail you about other stuff?
